### PR TITLE
add MacOS M1 arch

### PR DESCRIPTION
**Pull request by johnnychen94**
Really unsure if this is everything that requires.

### CODE REVIEW

**Comment by SaschaMann** [comment]
This doesn't seem to be working. Building it on this commit creates the same `versions.json` as on main: https://github.com/SaschaMann/Julia-versions.json/actions/runs/1083703401

Are these binaries available yet? If so, what's their URL? I can't find them on https://julialang.org/downloads/ and https://github.com/JuliaLang/julia/issues/36617 isn't resolved yet.

**Comment by johnnychen94** [comment]
https://julialang-s3.julialang.org/bin/mac/aarch64/1.7/julia-1.7.0-beta3-macaarch64.dmg

**Comment by SaschaMann** [comment]
It needs to be added to `tar_os(p::MacOS)` too so that the filename ends with `macaarch64.dmg` rather than `mac64.dmg`: https://github.com/SaschaMann/Julia-versions.json/commit/6c00938cf72290ecd4151d2abb15b761ffa2b2d8

I've tested it locally (which required Julia 1.5, apparently this script broke in 1.6), but I'll wait for the test build before merging: https://github.com/SaschaMann/Julia-versions.json/runs/3206252024

**Comment by johnnychen94** [comment]
Nice. You can open a new PR if you can't push to this branch. (Never figure out how to push to others PR)

**Comment by SaschaMann** [comment]
Thanks, that saves me the hassle of looking up how to push to another user's branch for the 154th time :D 

See #9

**Pull request closed without merging**
